/**
 * @author Sandro Martínez Pérez
 * @author Fernando David Gómez Gutierrez
 * @author Carlos Alberto Lara Hernández
 */
package GUIs.Alta;

import DB.Mammal_DB;
import java.util.Date;
import javax.swing.JOptionPane;

public class PanelAltaMamifero extends javax.swing.JPanel {
    
    private final Mammal_DB MDB;
    
    public PanelAltaMamifero() {
        initComponents();
        MDB = new Mammal_DB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Sexo = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ct_Nombre = new javax.swing.JTextField();
        ct_Color = new javax.swing.JTextField();
        jdc_fNacimiento = new com.toedter.calendar.JDateChooser();
        ct_Dientes = new javax.swing.JTextField();
        rb_Macho = new javax.swing.JRadioButton();
        rb_Hembra = new javax.swing.JRadioButton();
        cb_Categoria = new javax.swing.JComboBox<>();
        cb_TipoPelo = new javax.swing.JComboBox<>();
        b_Guardar = new javax.swing.JButton();
        b_Limpiar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta de Mamífero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 36), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Color:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Tipo de pelo:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("No. de Dientes:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Categoría:");

        ct_Nombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        ct_Color.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jdc_fNacimiento.setMaxSelectableDate(new Date());
        jdc_fNacimiento.setMinSelectableDate(new java.util.Date(946710062000L));
        jdc_fNacimiento.setPreferredSize(new java.awt.Dimension(100, 25));

        ct_Dientes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        bg_Sexo.add(rb_Macho);
        rb_Macho.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rb_Macho.setText("Macho");
        rb_Macho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_MachoActionPerformed(evt);
            }
        });

        bg_Sexo.add(rb_Hembra);
        rb_Hembra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rb_Hembra.setText("Hembra");

        cb_Categoria.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cb_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roedor", "Carnívoro", "Cetáceo", "Artiodáctilo", "Primate" }));
        cb_Categoria.setSelectedIndex(-1);

        cb_TipoPelo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cb_TipoPelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corto", "Mediano", "Largo" }));
        cb_TipoPelo.setSelectedIndex(-1);

        b_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.JPG"))); // NOI18N
        b_Guardar.setText("Guardar");
        b_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_GuardarActionPerformed(evt);
            }
        });

        b_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.JPG"))); // NOI18N
        b_Limpiar.setText("Limpiar");
        b_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Macho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Hembra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_Dientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_TipoPelo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(b_Limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_Guardar)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ct_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_Macho)
                    .addComponent(rb_Hembra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_TipoPelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ct_Dientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_Guardar)
                            .addComponent(b_Limpiar))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rb_MachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_MachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_MachoActionPerformed

    private void b_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimpiarActionPerformed
        ct_Color.setText("");
        ct_Nombre.setText("");
        ct_Dientes.setText("");
        cb_Categoria.setSelectedIndex(-1);
        cb_TipoPelo.setSelectedIndex(-1);
        jdc_fNacimiento.setDate(null);
        bg_Sexo.clearSelection();
    }//GEN-LAST:event_b_LimpiarActionPerformed

    private void b_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_GuardarActionPerformed
        boolean band = false;
        if(ct_Color.getText().equals("") ||
                ct_Nombre.getText().equals("") ||
                ct_Dientes.getText().equals("") ||
                cb_Categoria.getSelectedIndex() == -1 ||
                cb_TipoPelo.getSelectedIndex() == -1 ||
                jdc_fNacimiento.getDate() == null ||
                bg_Sexo.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
            band = true;
        } else {
            String name, color, categoria, tipoPelo, sexo;
            int dientes;
            Date fNacimiento;
            
            name = ct_Nombre.getText();
            try {
                dientes = Integer.parseInt(ct_Dientes.getText());
                if (dientes < 0 || dientes > 9280) {
                    JOptionPane.showMessageDialog(null, "El campo dientes debe ser un número entero positivo menor a 9280", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(null, "El campo dientes debe ser un número entero positivo menor a 9280", "ERROR", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            color = ct_Color.getText();
            categoria = cb_Categoria.getItemAt(cb_Categoria.getSelectedIndex());
            tipoPelo = cb_TipoPelo.getItemAt(cb_TipoPelo.getSelectedIndex());
            fNacimiento = jdc_fNacimiento.getDate();
            
            if(fNacimiento == null || fNacimiento.before(jdc_fNacimiento.getMinSelectableDate()) || fNacimiento.after(jdc_fNacimiento.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(rb_Macho.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            int res = MDB.insertarRegistro("mammal", name, color, sexo, new java.sql.Date(fNacimiento.getTime()), tipoPelo, dientes, categoria);
            if (res > 0) {
                this.b_LimpiarActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_b_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Guardar;
    private javax.swing.JButton b_Limpiar;
    private javax.swing.ButtonGroup bg_Sexo;
    private javax.swing.JComboBox<String> cb_Categoria;
    private javax.swing.JComboBox<String> cb_TipoPelo;
    private javax.swing.JTextField ct_Color;
    private javax.swing.JTextField ct_Dientes;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdc_fNacimiento;
    private javax.swing.JRadioButton rb_Hembra;
    private javax.swing.JRadioButton rb_Macho;
    // End of variables declaration//GEN-END:variables
}
