/**
 * @author Sandro Martínez Pérez
 * @author Fernando David Gómez Gutierrez
 * @author Carlos Alberto Lara Hernández
 */
package GUIs.Alta;

import DB.Veterinarian_DB;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

public class PanelAltaVeterinario extends javax.swing.JPanel {

    private final Veterinarian_DB VDB;
    public PanelAltaVeterinario() {
        initComponents();
        VDB = new Veterinarian_DB();
        Calendar maxDate = Calendar.getInstance();
        maxDate.add(Calendar.YEAR, -21);
        jdc_fNacimiento.setMaxSelectableDate(maxDate.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdc_fContratacion = new com.toedter.calendar.JDateChooser();
        jdc_fNacimiento = new com.toedter.calendar.JDateChooser();
        ct_Nombre = new javax.swing.JTextField();
        ct_Telefono = new javax.swing.JTextField();
        cb_Especialidad = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        b_Guardar = new javax.swing.JButton();
        b_Limpiar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta de Veterinario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 36), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Especialidad:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Fecha de Contratación:");

        jdc_fContratacion.setMaxSelectableDate(new Date());
        jdc_fContratacion.setMinSelectableDate(new java.util.Date(946710067000L));

        jdc_fNacimiento.setMinSelectableDate(new java.util.Date(-631126736000L));

        ct_Nombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        ct_Telefono.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        cb_Especialidad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cb_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirugía Veterinaria", "Medicina Interna Veterinaria", "Dermatología Veterinaria", "Oftamología Veterinaria", "Odontología Veterinaria", "Neurología Veterinaria", "Cardiología Veterinaria", "Reproducción Veterinaria", "Medicina de Emergencia ", "Cuidados Intensivos", "Medicina de Animales Exóticos", " ", " " }));
        cb_Especialidad.setSelectedIndex(-1);

        b_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.JPG"))); // NOI18N
        b_Guardar.setText("Guardar");
        b_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_GuardarActionPerformed(evt);
            }
        });

        b_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.JPG"))); // NOI18N
        b_Limpiar.setText("Limpiar");
        b_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Guardar)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Guardar)
                    .addComponent(b_Limpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(609, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_Nombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_fContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_fContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimpiarActionPerformed
        ct_Nombre.setText("");
        ct_Telefono.setText("");
        jdc_fContratacion.setDate(null);
        jdc_fNacimiento.setDate(null);
        cb_Especialidad.setSelectedIndex(-1); 
    }//GEN-LAST:event_b_LimpiarActionPerformed
    
    private void b_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_GuardarActionPerformed
        if(ct_Nombre.getText().equals("") ||
                ct_Telefono.getText().equals("") || 
                jdc_fContratacion.getDate() == null ||
                jdc_fNacimiento.getDate() == null ||
                cb_Especialidad.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String name, telefono, especialidad;
            name = ct_Nombre.getText();
            telefono = ct_Telefono.getText();
            especialidad = cb_Especialidad.getSelectedItem().toString();
            
            Date fNacimiento = jdc_fNacimiento.getDate();
            Date fContratacion = jdc_fContratacion.getDate();
            
            if(fNacimiento == null || fNacimiento.before(jdc_fNacimiento.getMinSelectableDate()) || fNacimiento.after(jdc_fNacimiento.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(fContratacion == null || fContratacion.before(jdc_fContratacion.getMinSelectableDate()) || fContratacion.after(jdc_fContratacion.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Calendar calInicio = Calendar.getInstance();
            calInicio.setTime(fNacimiento);

            Calendar calFin = Calendar.getInstance();
            calFin.setTime(fContratacion);
            
            int diferenciaAnios = calFin.get(Calendar.YEAR) - calInicio.get(Calendar.YEAR);
            
            if (calFin.get(Calendar.DAY_OF_YEAR) < calInicio.get(Calendar.DAY_OF_YEAR)) {
                diferenciaAnios--;
            }
            if(diferenciaAnios < 21 || diferenciaAnios > 80) {
                JOptionPane.showMessageDialog(null, "La fecha de contratación debe ser 21 años posterior a la de nacimiento y menor a 80", "ERROR", JOptionPane.ERROR_MESSAGE);
                calInicio.add(Calendar.YEAR, 21);
                jdc_fContratacion.setMinSelectableDate(calInicio.getTime());
                return;
            }
            int res = VDB.insertarRegistro(name, especialidad, telefono, new java.sql.Date(fNacimiento.getTime()), new java.sql.Date(fContratacion.getTime()));
            if (res > 0) {
                this.b_LimpiarActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_b_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Guardar;
    private javax.swing.JButton b_Limpiar;
    private javax.swing.JComboBox<String> cb_Especialidad;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JTextField ct_Telefono;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdc_fContratacion;
    private com.toedter.calendar.JDateChooser jdc_fNacimiento;
    // End of variables declaration//GEN-END:variables
}
