/**
 * @author Sandro Martínez Pérez
 * @author Fernando David Gómez Gutierrez
 * @author Carlos Alberto Lara Hernández
 */
package GUIs.Listar;

import DB.Bird_DB;
import java.awt.Component;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PanelListarAves extends javax.swing.JPanel {

    private final Bird_DB BDB;
    
    public PanelListarAves() {
        initComponents();
        BDB = new Bird_DB();
        this.limpiar();
        this.listar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Sexo = new javax.swing.ButtonGroup();
        bg_Vuela = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Aves = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        b_Eliminar = new javax.swing.JButton();
        b_Actualizar = new javax.swing.JButton();
        b_Limpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ct_idAve = new javax.swing.JTextField();
        ct_Nombre = new javax.swing.JTextField();
        ct_Color = new javax.swing.JTextField();
        rb_Macho = new javax.swing.JRadioButton();
        rb_Hembra = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_TipoPico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb_Si = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rb_No = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_Tamano = new javax.swing.JComboBox<>();
        jdc_fNacimiento = new com.toedter.calendar.JDateChooser();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Aves", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jt_Aves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt_Aves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_AvesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Aves);

        jLabel1.setText("Aves registradas en la base de datos:");

        b_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarR.png"))); // NOI18N
        b_Eliminar.setText("Eliminar");
        b_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EliminarActionPerformed(evt);
            }
        });

        b_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alta1.JPG"))); // NOI18N
        b_Actualizar.setText("Actualizar");
        b_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ActualizarActionPerformed(evt);
            }
        });

        b_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.JPG"))); // NOI18N
        b_Limpiar.setText("Limpiar");
        b_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Actualizar)
                .addGap(18, 18, 18)
                .addComponent(b_Eliminar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Eliminar)
                    .addComponent(b_Actualizar)
                    .addComponent(b_Limpiar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Ave"));

        ct_idAve.setEnabled(false);
        ct_idAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_idAveActionPerformed(evt);
            }
        });

        bg_Sexo.add(rb_Macho);
        rb_Macho.setText("Macho");

        bg_Sexo.add(rb_Hembra);
        rb_Hembra.setText("Hembra");

        jLabel2.setText("ID del Ave:");

        jLabel3.setText("Nombre:");

        cb_TipoPico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pico Cónico", "Pico Gancho", "Pico Conico-Curvado", "Pico de Espátula", "Pico Aguja", "Pico Perforador", "Pico Tubular", "Pico Martillo" }));
        cb_TipoPico.setSelectedIndex(-1);

        jLabel4.setText("Color:");

        jLabel8.setText("Capacidad de Volar:");

        jLabel5.setText("Sexo:");

        bg_Vuela.add(rb_Si);
        rb_Si.setText("Sí");

        jLabel6.setText("Fecha de Nacimiento:");

        bg_Vuela.add(rb_No);
        rb_No.setText("No");

        jLabel7.setText("Tipo de pico:");

        jLabel9.setText("Tamaño:");

        cb_Tamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande", "Muy Grande", "Envergadura de Alas Grande" }));
        cb_Tamano.setSelectedIndex(-1);

        jdc_fNacimiento.setMaxSelectableDate(new Date());
        jdc_fNacimiento.setMinSelectableDate(new java.util.Date(946710082000L));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Si)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_No)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idAve, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_TipoPico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Macho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Hembra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ct_idAve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ct_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cb_TipoPico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_Macho)
                    .addComponent(rb_Hembra))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rb_Si)
                    .addComponent(rb_No)
                    .addComponent(jLabel9)
                    .addComponent(cb_Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ct_idAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_idAveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_idAveActionPerformed

    private void b_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EliminarActionPerformed
        int res = 0;
        int fila = jt_Aves.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un registro de la tabla",
                    "Eliminar registro", 1);
        } else {
            try {
                res = BDB.eliminarRegistro(Integer.parseInt(jt_Aves.getValueAt(fila, 0).toString()));
            } catch (SQLException ex) {
                Logger.getLogger(PanelListarVeterinarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (res > 0) {
                this.limpiar();
                this.listar();
            }
        }
    }//GEN-LAST:event_b_EliminarActionPerformed

    private void b_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ActualizarActionPerformed
        if(cb_Tamano.getSelectedIndex() == -1 || 
                cb_TipoPico.getSelectedIndex() == -1 || 
                ct_Color.getText().equals("") ||
                ct_Nombre.getText().equals("") || 
                jdc_fNacimiento.getDate() == null || 
                bg_Sexo.getSelection() == null ||
                bg_Vuela.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        } else {
            String name, color, tamano, sexo, tipoPico;
            int vuela;
            Date fNacimiento;
            color = ct_Color.getText();
            tamano = cb_Tamano.getItemAt(cb_Tamano.getSelectedIndex());
            tipoPico = cb_TipoPico.getItemAt(cb_TipoPico.getSelectedIndex());
            fNacimiento = jdc_fNacimiento.getDate();
            name = ct_Nombre.getText();
            
            if(fNacimiento == null || fNacimiento.before(jdc_fNacimiento.getMinSelectableDate()) || fNacimiento.after(jdc_fNacimiento.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(rb_No.isSelected()) {
                vuela = 0;
            } else {
                vuela = 1;
            }
            
            if(rb_Macho.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            
            int id = Integer.parseInt(ct_idAve.getText());
            int res = BDB.actualizarRegistro(name, color, sexo, new java.sql.Date(fNacimiento.getTime()), tipoPico, vuela, tamano, id);
            if (res > 0) {
                this.limpiar();
                this.listar();
            }
        }
    }//GEN-LAST:event_b_ActualizarActionPerformed

    private void jt_AvesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_AvesMouseClicked
        b_Actualizar.setEnabled(true);
        b_Eliminar.setEnabled(true);
        b_Limpiar.setEnabled(true);
        jPanel2.setEnabled(true);
        for (Component component : jPanel2.getComponents ()) { component.setEnabled (true); }
        ct_idAve.setEnabled(false);
        
        int fila = jt_Aves.getSelectedRow();
        ct_idAve.setText(jt_Aves.getValueAt(fila, 0).toString());
        ct_Nombre.setText(jt_Aves.getValueAt(fila, 1).toString());
        ct_Color.setText(jt_Aves.getValueAt(fila, 2).toString());
        cb_TipoPico.setSelectedItem(jt_Aves.getValueAt(fila, 5).toString());
        cb_Tamano.setSelectedItem(jt_Aves.getValueAt(fila, 7).toString());
        
        if(jt_Aves.getValueAt(fila, 3).toString().equals("F")) {
            rb_Hembra.setSelected(true);
        } else {
            rb_Macho.setSelected(true);
        }
        
        if(jt_Aves.getValueAt(fila, 6).toString().equals("Si")) {
            rb_Si.setSelected(true);
        } else {
            rb_No.setSelected(true);
        }
        
        String fecha = jt_Aves.getValueAt(fila, 4).toString();
        Date fechaN;
        try {
            fechaN = new SimpleDateFormat("yyyy-MM-dd").parse(fecha);
        } catch (ParseException e) {
            System.out.println("Error en fechas.....");
            return;
        }
        jdc_fNacimiento.setDate(fechaN);
    }//GEN-LAST:event_jt_AvesMouseClicked

    private void b_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_b_LimpiarActionPerformed
   
     private void listar() {
        jt_Aves.setModel(BDB.getDatos());
        
    }
     
    public void limpiar() {
        cb_Tamano.setSelectedIndex(-1);
        cb_TipoPico.setSelectedIndex(-1);
        bg_Sexo.clearSelection();
        bg_Vuela.clearSelection();
        ct_Color.setText("");
        ct_Nombre.setText("");
        jdc_fNacimiento.setDate(null);
        for (Component component : jPanel2.getComponents ()) { component.setEnabled (false); }
        b_Actualizar.setEnabled(false);
        b_Eliminar.setEnabled(false);
        b_Limpiar.setEnabled(false);
        jPanel2.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Actualizar;
    private javax.swing.JButton b_Eliminar;
    private javax.swing.JButton b_Limpiar;
    private javax.swing.ButtonGroup bg_Sexo;
    private javax.swing.ButtonGroup bg_Vuela;
    private javax.swing.JComboBox<String> cb_Tamano;
    private javax.swing.JComboBox<String> cb_TipoPico;
    private javax.swing.JTextField ct_Color;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JTextField ct_idAve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_fNacimiento;
    private javax.swing.JTable jt_Aves;
    private javax.swing.JRadioButton rb_Hembra;
    private javax.swing.JRadioButton rb_Macho;
    private javax.swing.JRadioButton rb_No;
    private javax.swing.JRadioButton rb_Si;
    // End of variables declaration//GEN-END:variables
}
