/**
 * @author Sandro Martínez Pérez
 * @author Fernando David Gómez Gutierrez
 * @author Carlos Alberto Lara Hernández
 */
package GUIs.Listar;

import DB.Veterinarian_DB;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PanelListarVeterinarios extends javax.swing.JPanel {

    private final Veterinarian_DB VDB;
    public PanelListarVeterinarios() {
        initComponents();
        VDB = new Veterinarian_DB();
        this.limpiar();
        this.listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ct_idVeterinario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ct_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_Especialidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ct_Telefono = new javax.swing.JTextField();
        jdc_fNacimiento = new com.toedter.calendar.JDateChooser();
        jdc_fContratacion = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Veterinarios = new javax.swing.JTable();
        b_Limpiar = new javax.swing.JButton();
        b_Eliminar = new javax.swing.JButton();
        b_Actualizar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Veterinarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Veterinario"));

        jLabel1.setText("ID del Veterinario:");

        ct_idVeterinario.setEnabled(false);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Especialidad:");

        cb_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirugía Veterinaria", "Medicina Interna Veterinaria", "Dermatología Veterinaria", "Oftamología Veterinaria", "Odontología Veterinaria", "Neurología Veterinaria", "Cardiología Veterinaria", "Reproducción Veterinaria", "Medicina de Emergencia ", "Cuidados Intensivos", "Medicina de Animales Exóticos" }));
        cb_Especialidad.setSelectedIndex(-1);

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setText("Fecha de Contratación:");

        jdc_fContratacion.setMaxSelectableDate(new Date());
        jdc_fContratacion.setMinSelectableDate(new java.util.Date(946710102000L));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jdc_fContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(ct_idVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jdc_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jdc_fContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Veterinarios registrados en la base de datos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jt_Veterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt_Veterinarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_VeterinariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Veterinarios);

        b_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.JPG"))); // NOI18N
        b_Limpiar.setText("Limpiar");
        b_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimpiarActionPerformed(evt);
            }
        });

        b_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarR.png"))); // NOI18N
        b_Eliminar.setText("Eliminar");
        b_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EliminarActionPerformed(evt);
            }
        });

        b_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alta1.JPG"))); // NOI18N
        b_Actualizar.setText("Actualizar");
        b_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(b_Limpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_Actualizar)
                                        .addGap(93, 93, 93))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_Eliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addGap(18, 36, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_Eliminar)
                            .addComponent(b_Actualizar)
                            .addComponent(b_Limpiar))
                        .addGap(68, 68, 68))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EliminarActionPerformed
        int res = 0;
        int fila = jt_Veterinarios.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un registro de la tabla",
                    "Eliminar registro", 1);
        } else {
            try {
                res = VDB.eliminarRegistro(Integer.parseInt(jt_Veterinarios.getValueAt(fila, 0).toString()));
            } catch (NumberFormatException ex) {
                Logger.getLogger(PanelListarVeterinarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (res > 0) {
                this.limpiar();
                this.listar();
            }
        }
    }//GEN-LAST:event_b_EliminarActionPerformed

    private void jt_VeterinariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_VeterinariosMouseClicked
        b_Actualizar.setEnabled(true);
        b_Eliminar.setEnabled(true);
        jPanel1.setEnabled(true);
        b_Limpiar.setEnabled(true);
        for (Component component : jPanel1.getComponents ()) { component.setEnabled (true); }
        ct_idVeterinario.setEnabled(false);
        
        int fila = jt_Veterinarios.getSelectedRow();
        ct_idVeterinario.setText(jt_Veterinarios.getValueAt(fila, 0).toString());
        ct_Nombre.setText(jt_Veterinarios.getValueAt(fila, 1).toString());
        ct_Telefono.setText(jt_Veterinarios.getValueAt(fila, 3).toString());
        cb_Especialidad.setSelectedItem(jt_Veterinarios.getValueAt(fila, 2).toString());
        
        String fecha1 = jt_Veterinarios.getValueAt(fila, 4).toString();
        Date fechaN;
        try {
            fechaN = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jdc_fNacimiento.setDate(fechaN);
        
        String fecha2 = jt_Veterinarios.getValueAt(fila, 5).toString();
        Date fechaH;
        try {
            fechaH = new SimpleDateFormat("yyyy-MM-dd").parse(fecha2);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jdc_fContratacion.setDate(fechaH);
    }//GEN-LAST:event_jt_VeterinariosMouseClicked

    private void b_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ActualizarActionPerformed
        if(ct_Nombre.getText().equals("") ||
                ct_Telefono.getText().equals("") || 
                jdc_fContratacion.getDate() == null ||
                jdc_fNacimiento.getDate() == null ||
                cb_Especialidad.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String name, telefono, especialidad;
            name = ct_Nombre.getText();
            telefono = ct_Telefono.getText();
            especialidad = cb_Especialidad.getSelectedItem().toString();
            
            Date fNacimiento = jdc_fNacimiento.getDate();
            Date fContratacion = jdc_fContratacion.getDate();
            if(fNacimiento == null || fNacimiento.before(jdc_fNacimiento.getMinSelectableDate()) || fNacimiento.after(jdc_fNacimiento.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(fContratacion == null || fContratacion.before(jdc_fContratacion.getMinSelectableDate()) || fContratacion.after(jdc_fContratacion.getMaxSelectableDate())) {
                JOptionPane.showMessageDialog(null, "Error en fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Calendar calInicio = Calendar.getInstance();
            calInicio.setTime(fNacimiento);

            Calendar calFin = Calendar.getInstance();
            calFin.setTime(fContratacion);
            
            int diferenciaAnios = calFin.get(Calendar.YEAR) - calInicio.get(Calendar.YEAR);
            
            if (calFin.get(Calendar.DAY_OF_YEAR) < calInicio.get(Calendar.DAY_OF_YEAR)) {
                diferenciaAnios--;
            }
            if(diferenciaAnios < 21 || diferenciaAnios > 80) {
                JOptionPane.showMessageDialog(null, "La fecha de contratación debe ser 21 años posterior a la de nacimiento y menor a 80", "ERROR", JOptionPane.ERROR_MESSAGE);
                calInicio.add(Calendar.YEAR, 21);
                jdc_fContratacion.setMinSelectableDate(calInicio.getTime());
                return;
            }
            int id = Integer.parseInt(ct_idVeterinario.getText());
            int res = VDB.actualizarRegistro(name, especialidad, telefono, new java.sql.Date(fNacimiento.getTime()), new java.sql.Date(fContratacion.getTime()), id);
            if (res > 0) {
                this.limpiar();
                this.listar();
            }
            
        }
    }//GEN-LAST:event_b_ActualizarActionPerformed

    private void b_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_b_LimpiarActionPerformed
    public void limpiar() {
        ct_Nombre.setText("");
        ct_Telefono.setText("");
        ct_idVeterinario.setText("");
        jdc_fContratacion.setDate(null);
        jdc_fNacimiento.setDate(null);
        cb_Especialidad.setSelectedIndex(-1);
        for (Component component : jPanel1.getComponents ()) { component.setEnabled (false); }
        b_Actualizar.setEnabled(false);
        b_Eliminar.setEnabled(false);
        b_Limpiar.setEnabled(false);
        jPanel1.setEnabled(false);
    }
    
    private void listar() {
        jt_Veterinarios.setModel(VDB.getDatos());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Actualizar;
    private javax.swing.JButton b_Eliminar;
    private javax.swing.JButton b_Limpiar;
    private javax.swing.JComboBox<String> cb_Especialidad;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JTextField ct_Telefono;
    private javax.swing.JTextField ct_idVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_fContratacion;
    private com.toedter.calendar.JDateChooser jdc_fNacimiento;
    private javax.swing.JTable jt_Veterinarios;
    // End of variables declaration//GEN-END:variables
}
